---
title: "Exploration"
output: 
  github_document:
    html_preview: TRUE
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
set.seed(1234)
source("2-code/exploration.R")
```


---

## ALL DATA

<details>
  <summary> Click to Open </summary>




### BASIC EXPLORATION

```{r jitters, fig.height=12, fig.width=12}

bgc_long %>% 
  ggplot(aes(x = abbreviated, y = value, color = Location))+
  geom_jitter(width = 0.3)+
  facet_wrap(~analysis_type, scales = "free")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


---

### CORRELATIONS AND PCAs

**PCA**
```{r pca, fig.height=10, fig.width=12}
compute_pca(bgc_wide)
```


**Correlations**
```{r corr_plot}
compute_correlations(bgc_wide)
```


---

### MAPS


```{r maps}

make_map(bgc_wide, VAR = "SO4S", TITLE = "sulfate")
make_map(bgc_wide, VAR = "TC")
make_map(bgc_wide, VAR = "TN")
make_map(bgc_wide, VAR = "TS")
make_map(bgc_wide, VAR = "TKN")


make_map(bgc_wide, VAR = "Ca")
make_map(bgc_wide, VAR = "Mg")
make_map(bgc_wide, VAR = "Na")
make_map(bgc_wide, VAR = "K")
make_map(bgc_wide, VAR = "CEC")
make_map(bgc_wide, VAR = "Bases")

make_map(bgc_wide, VAR = "Zn")
make_map(bgc_wide, VAR = "Cu")

make_map(bgc_wide, VAR = "NO3N")
make_map(bgc_wide, VAR = "NH4N")

make_map(bgc_wide, VAR = "Clay")
make_map(bgc_wide, VAR = "Sand")

make_map(bgc_wide, VAR = "WEOC")
make_map(bgc_wide, VAR = "MBC")

```


</details>

----


## SUBSET DATA
<details>
  <summary> Session Info </summary>

```{r}

data2 = read_csv("1-data/bgc_data.csv") %>% dplyr::select(-Total_Sulfur_pct, -notes)

bgc_long2 = process_bgc_data(data2, analysis_key, metadata_biome)$long
bgc_wide2 = process_bgc_data(data2, analysis_key, metadata_biome)$wide

```


```{r jitters2, fig.height=12, fig.width=12}

bgc_long2 %>% 
  ggplot(aes(x = abbreviated, y = value, color = Location))+
  geom_jitter(width = 0.3)+
  facet_wrap(~analysis_type, scales = "free")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


---

### CORRELATIONS AND PCAs

**PCA**
```{r pca2, fig.height=10, fig.width=12}
compute_pca(bgc_wide2)
```


**Correlations**
```{r corr_plot2}
compute_correlations(bgc_wide2)
```


---

### MAPS


```{r maps2}

make_map(bgc_wide2, VAR = "SO4S", TITLE = "sulfate")
make_map(bgc_wide2, VAR = "TC")
make_map(bgc_wide2, VAR = "TN")
make_map(bgc_wide2, VAR = "TKN")


make_map(bgc_wide2, VAR = "Ca")
make_map(bgc_wide2, VAR = "Mg")
make_map(bgc_wide2, VAR = "Na")
make_map(bgc_wide2, VAR = "K")
make_map(bgc_wide2, VAR = "CEC")
make_map(bgc_wide2, VAR = "Bases")

make_map(bgc_wide2, VAR = "Zn")
make_map(bgc_wide2, VAR = "Cu")

make_map(bgc_wide2, VAR = "NO3N")
make_map(bgc_wide2, VAR = "NH4N")

make_map(bgc_wide2, VAR = "Clay")
make_map(bgc_wide2, VAR = "Sand")

make_map(bgc_wide2, VAR = "WEOC")
make_map(bgc_wide2, VAR = "MBC")

```




</details>

---

## Session Info 

<details>
  <summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>